# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo Job 1 !
    displayName: 'Job1 : Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2 is Running!
    displayName: 'Job 2 Proceding to Run'

- job: Job3
  dependsOn: Job1
  steps:
  - script: echo Job3 is Running!
    displayName: 'Job 3 Proceding to Run'

- job: Job4
  dependsOn:
  - Job2
  - Job3
  steps:
  - script: echo Job4 is Running!
    displayName: 'Job 4 Proceding to Run'