trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job: FirstJob 
    steps: 
    - bash: echo Build First Job
    - bash: java -version
      displayName: Java Version     
    - bash: mvn --version
      displayName: Maven Version
    - bash: python --version
      displayName: Python Version
    - bash: node --version
      displayName: Node Version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
      displayName: Listing Artifact Staging Directory Before copy
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - bash: ls -R $(Build.ArtifactStagingDirectory)
      displayName: Listing Artifact Staging Directory After copy

    # - bash: echo $(Build.ArtifactStagingDirectory)
    #   displayName: ArtifactStagingDirectory
    # - bash: echo $(Build.BuildNumber)
    #   displayName: BuildNumber
    # - bash: echo $(Build.BuildId)
    #   displayName: BuildId
    # - bash: echo $(Build.SourceBranchName)
    #   displayName: SourceBranchName            
    # - bash: echo $(Build.SourcesDirectory)
    #   displayName: SourceDirectory
    # - bash: echo $(System.DefaultWorkingDirectory)
    #   displayName: DefaultWorkingDirectory
    # - bash: echo ls -R $(System.DefaultWorkingDirectory)
    #   displayName: ArtifactStagingDirectory
    # - bash: echo $(Build.BinariesDirectory)
    #   displayName: Build.BinariesDirectory
    # - bash: echo $(Build.Repository.LocalPath)
    #   displayName: Build.Repository.LocalPath      
    # - bash: echo $System.AccessToken
    #   displayName: AccessToken                         
  # - job: SecondJob 
  #   steps: 
  #   - bash: echo Build SecondJob Job    
# - stage: DevDeploy
#   variables:
#    environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps: 
#     - bash: echo $(environment)Deploy Job
# - stage: QaDeploy
#   variables:
#    environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QaDeployJob
#     steps: 
#     - bash: echo $(environment)Deploy Job
# - stage: ProdDeploy
#   variables:
#    environment: Prod
#   dependsOn: 
#   - DevDeploy
#   - QaDeploy
#   jobs:
#   - job: ProdDeployJob
#     steps: 
#     - bash: echo $(environment)Deploy Job